name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true  # optional, default is false
          tags: nexcvon/ssh:latest
          platforms: linux/amd64,linux/arm/v7 # optional
